import { describe, expect, it } from "vitest";
import { siteMetadata } from "./site-metadata";

describe("siteMetadata", () => {
  it("題名と説明を家計簿向けにする", () => {
    expect(siteMetadata.title).toBe("家計簿");
    expect(siteMetadata.description).toMatch(/家計/);
    expect(siteMetadata.title).not.toMatch(/Create Next App/i);
    expect(siteMetadata.description).not.toMatch(/Generated by create next app/i);
  });
});
